import { ALL_MODULES } from '../modules';
import type { RepoConfig } from '../modules/types';
import { SnippetBlock } from './SnippetBlock';
import { Download } from 'lucide-react';

interface Props {
  config: RepoConfig;
}

function generateBashScript(config: RepoConfig): string {
  const selectedModules = ALL_MODULES.filter(m => config.selectedManagers.includes(m.id));
  if (selectedModules.length === 0) return '#!/usr/bin/env bash\nset -euo pipefail\n\n# No package managers selected.';

  const authBlock = config.authEnabled
    ? `# Replace these placeholder values with your actual credentials\nUSERNAME="${config.username ? config.username : 'YOUR_USERNAME'}"\nTOKEN="${config.token ? config.token : 'YOUR_TOKEN'}"\n\n`
    : '';

  const sections = selectedModules.map(mod => {
    const script = mod.scriptTemplate(config);
    return `# === ${mod.label} ===\n${script}`;
  });

  return [
    `#!/usr/bin/env bash`,
    `set -euo pipefail`,
    ``,
    authBlock.trim(),
    ``,
    sections.join('\n\n'),
    ``,
    `echo "Setup complete!"`,
  ].filter((line, i, arr) => !(line === '' && arr[i - 1] === '')).join('\n');
}

function generatePowerShellScript(config: RepoConfig): string {
  const selectedModules = ALL_MODULES.filter(m => config.selectedManagers.includes(m.id));
  if (selectedModules.length === 0) return '# No package managers selected.';

  const authBlock = config.authEnabled
    ? `# Replace these placeholder values with your actual credentials\n$USERNAME = "${config.username ? config.username : 'YOUR_USERNAME'}"\n$TOKEN = "${config.token ? config.token : 'YOUR_TOKEN'}"\n\n`
    : '';

  const sections = selectedModules.map(mod => {
    const script = mod.psScriptTemplate(config);
    return `# === ${mod.label} ===\n${script}`;
  });

  return [
    `# Workstation Package Manager Setup Script`,
    `# Generated by workstation-setup`,
    ``,
    authBlock.trim(),
    ``,
    sections.join('\n\n'),
    ``,
    `Write-Host "Setup complete!"`,
  ].filter((line, i, arr) => !(line === '' && arr[i - 1] === '')).join('\n');
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ScriptExportPanel({ config }: Props) {
  const isWindows = config.os === 'windows';
  const script = isWindows ? generatePowerShellScript(config) : generateBashScript(config);
  const filename = isWindows ? 'setup-package-managers.ps1' : 'setup-package-managers.sh';
  const mimeType = isWindows ? 'text/plain' : 'text/x-shellscript';
  const language = isWindows ? 'powershell' : 'bash';

  const handleDownload = () => {
    downloadFile(script, filename, mimeType);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-gray-600">
          {isWindows ? 'PowerShell script (.ps1)' : 'Bash script (.sh)'} for {config.os}
        </p>
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors"
        >
          <Download size={15} />
          Download Script
        </button>
      </div>
      <SnippetBlock code={script} language={language} title={filename} />
    </div>
  );
}

// Export generators for testing
export { generateBashScript, generatePowerShellScript };
